%% Student Information
%%
% 
%  Student Name: Regis Zhao
%
%%
% 
%  Student Number: 1007070660
%
%% Exercise 1

% IMPROVED EULER'S METHOD FOR SYSTEM OF 2 EQUATIONS

% function [t, x] = solvesystem_zhaoregi(f1,f2,t0,tN,x0,h)
%     t = t0:h:tN;
%     x = NaN(2, length(t));
%     x(:,1) = x0;
%     for i = 2:length(t)
%         m_prev = [f1(t(i-1), x(1,i-1), x(2,i-1)) f2(t(i-1), x(1,i-1), x(2,i-1))]';
%         sol_cur = x(:,i-1) + m_prev.*h;
%         m_cur = [f1(t(i), sol_cur(1), sol_cur(2)) f2(t(i), sol_cur(1), sol_cur(2))]';
%         S = (m_prev + m_cur) ./ 2;
%         x(:,i) = x(:,i-1) + S.*h;
%     end
% end

%% Exercise 2

% Improved Euler Approximation
f1 = @(t,x1,x2) (x1/2) - (2*x2);
f2 = @(t,x1,x2) (5*x1) - x2;
x0 = [1 1]'; t0 = 0; tN = 4*pi; h = 0.05;
[t, x] = solvesystem_zhaoregi(f1, f2, t0, tN, x0, h);

% Exact Solution:
% x1 = c1*exp(-t/4)*(3cosvt - sqrt(151)*sinvt) + c2*exp(-t/4)*(3sinvt +
% sqrt(151)*cosvt)
% x2 = c1*exp(-t/4)*(20cosvt) + c2*exp(-t/4)*(20sinvt)
% where c1 = 1/20, c2 = 17/(20sqrt(151)), v = sqrt(151)/4
c1 = 1/20;
c2 = 17/(20*sqrt(151));
v = (sqrt(151))/4;
u1 = 3.*cos(v.*t) - sqrt(151).*sin(v.*t);
u2 = 20.*cos(v.*t);
w1 = 3.*sin(v.*t) + sqrt(151).*cos(v.*t);
w2 = 20.*sin(v.*t);
exp_t = exp(-t./4);
x1_exact = c1.*exp_t.*u1 + c2.*exp_t.*w1;
x2_exact = c1.*exp_t.*u2 + c2.*exp_t.*w2;

% Plotting phase portraits
plot(x(1,:), x(2,:), x1_exact, x2_exact);
title('Phase portrait generated by improved Euler approximation and exact solution');
legend('Improved Euler Approximation', 'Exact Solution', "Euler's Method from iode");
xlabel('x1'); ylabel('x2');

%% Exercise 3

f = @(t, x) [(x(1)/2)-(2*x(2)) ; (5*x(1))-x(2)];
x_euler = euler(f, x0, t);
plot(x(1,:), x(2,:), x1_exact, x2_exact, x_euler(1,:), x_euler(2,:));
title('Phase portraits generated using different methods');
legend('Improved Euler Approximation', 'Exact Solution', "Euler's Method from iode");
xlabel('x1'); ylabel('x2');

% The improved Euler's method is very accurate to the exact
% solution - there is little discrepancy between the two solutions.
% Contrarily, the solution approximated using Euler's method is
% significantly different from that of the improved Euler's method and the
% exact solution. The most prominent difference between Euler's
% approximation and the other two is that it decays much more slowly.

%% Exercise 4

% Refer to Q4.pdf for answers.